name: Deploy static content to Pages

on:
  # Chạy tự động mỗi khi có lệnh Push (commit) lện nhánh main
  push:
    branches: ['main']

  # Cho phép chạy deploy thủ công từ giao diện tab Actions
  workflow_dispatch:

# Quyền hạn Github Token cần thiết để upload artifact lên branch Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Tránh deploy trùng xếp lên nhau
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Cấu hình một job deploy chung
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Thư mục xuất ra sau khi build của Vite mặc định là dist
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
